# NumPy Assignment --- Extracting Submatrice
## Description
In this assignment, we are given a randomly generated 10$ \times $10 matrix, and we aim to output all the submatrice of the original matrix.

In [1]:
import numpy as np


In [2]:
Z = np.random.randint(0,5,(10,10))
print(Z)

[[1 2 0 2 0 3 0 0 3 4]
 [0 0 2 0 0 2 0 3 1 0]
 [0 2 2 1 3 2 2 2 3 4]
 [1 1 2 4 4 0 2 1 3 3]
 [1 0 2 1 1 2 4 4 2 1]
 [0 2 3 3 2 4 1 1 3 4]
 [4 3 4 1 2 4 0 4 3 3]
 [1 2 0 0 3 0 1 3 1 2]
 [4 0 3 4 2 2 1 2 1 1]
 [0 3 0 4 0 3 2 3 4 2]]


### Your implementation
Enter your code below!

### Key
Skip upon first reading!

In [4]:
from numpy.lib import stride_tricks

In [5]:
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 2 0]
   [0 0 2]
   [0 2 2]]

  [[2 0 2]
   [0 2 0]
   [2 2 1]]

  [[0 2 0]
   [2 0 0]
   [2 1 3]]

  [[2 0 3]
   [0 0 2]
   [1 3 2]]

  [[0 3 0]
   [0 2 0]
   [3 2 2]]

  [[3 0 0]
   [2 0 3]
   [2 2 2]]

  [[0 0 3]
   [0 3 1]
   [2 2 3]]

  [[0 3 4]
   [3 1 0]
   [2 3 4]]]


 [[[0 0 2]
   [0 2 2]
   [1 1 2]]

  [[0 2 0]
   [2 2 1]
   [1 2 4]]

  [[2 0 0]
   [2 1 3]
   [2 4 4]]

  [[0 0 2]
   [1 3 2]
   [4 4 0]]

  [[0 2 0]
   [3 2 2]
   [4 0 2]]

  [[2 0 3]
   [2 2 2]
   [0 2 1]]

  [[0 3 1]
   [2 2 3]
   [2 1 3]]

  [[3 1 0]
   [2 3 4]
   [1 3 3]]]


 [[[0 2 2]
   [1 1 2]
   [1 0 2]]

  [[2 2 1]
   [1 2 4]
   [0 2 1]]

  [[2 1 3]
   [2 4 4]
   [2 1 1]]

  [[1 3 2]
   [4 4 0]
   [1 1 2]]

  [[3 2 2]
   [4 0 2]
   [1 2 4]]

  [[2 2 2]
   [0 2 1]
   [2 4 4]]

  [[2 2 3]
   [2 1 3]
   [4 4 2]]

  [[2 3 4]
   [1 3 3]
   [4 2 1]]]


 [[[1 1 2]
   [1 0 2]
   [0 2 3]]

  [[1 2 4]
   [0 2 1]
   [2 3 3]]

  [[2 4 4]
   [2 1 1]
   [3 3 2]]

  [[4 4 0]
   [1 1 2]
   [3 2 4]]

  [[4 0 2]
   